import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Book Club</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section>
                메인페이지
            </section>
        </>
    );
}
